### ISSUE TITLE
Unable to open Plugin.py

### ISSUE THREAD

**Issue by dutch2005** [tixi/Domoticz-Tuya-SmartPlug-Plugin#6]
Domoticz version: Domoticz V4.9700 

Issue Tthe platform you are using: Raspberry pi3b+
OS: Debian Stretch (32 bits); version 9.x
Python Version used: 3.5.3

Error:

2019-01-29 20:58:17.909 Error: (tixi_tuya_smartplug_plugin) failed to load 'plugin.py', Python Path used was '/root/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin/:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-arm-linux-gnueabihf:/usr/lib/python3.5/lib-dynload'.

Python Location:

root@raspberrypi:~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin# ls -lh /usr/bin/python3
lrwxrwxrwx 1 root root 9 Jan 20  2017 /usr/bin/python3 -> python3.5
root@raspberrypi:~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin# which python3
/usr/bin/python3
root@raspberrypi:~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin# ls -lh /usr/bin/python3.5
-rwxr-xr-x 2 root root 3.8M Sep 27 19:25 /usr/bin/python3.5
root@raspberrypi:~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin#

Installed PyAES:  pyaes in /usr/local/lib/python3.5/dist-packages

Please advise on how to fix it

**Comment by tixi** [comment]
Read the Readme file !!!

**Comment by dutch2005** [comment]
Thnx for the "friendly" reply....

Looked again at the readme file, found the issue.

Issue was that you assume that I run the application as the "pi" user, I dont, hence i had to chance the location

Your code

> cd ~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin
> ln -s /home/pi/.local/lib/python3.5/site-packages/Crypto Crypto

How to make it workable for me:

> cd ~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin
> ln -s /usr/lib/python3/dist-packages/Crypto Crypto
> 

Why:

> pip3 show pycrypto
> Name: pycrypto
> Version: 2.6.1
> Summary: Cryptographic modules for Python.
> Home-page: http://www.pycrypto.org/
> Author: Dwayne C. Litzenberger
> Author-email: dlitz@dlitz.net
> License: UNKNOWN
> Location: /usr/lib/python3/dist-packages
> Requires: 
>
