### ISSUE TITLE
no device

### ISSUE THREAD

**Issue by geertvercamer** [tixi/Domoticz-Tuya-SmartPlug-Plugin#7]
Hi,

I'm sure I have the right ID/Key/... as I can access the devices with both Node-Red and python (turnON / turnOFF)

My problem is that after adding the hardware into Domoticz, no devices are created.
In the log I see these lines repeated 15".

Anyone's got an idea?
Is there some more elaborate log available?

Thanks

**Comment by tixi** [comment]
seems to be related to a domoticz installation on windows
